### ISSUE TITLE
Left bar content overlap 

### ISSUE THREAD

**Issue by p0bo** [KanashiiDev/personal-stylesheets#3] opened 2024-06-30 16:25 UTC
**Describe the bug**
The Anime details content in the left bar is overlapped 
The green marked ones are anilist tags they look normal , not sure if the red marked details look is intended or not 

**Screenshots**
> ![Screenshot_2024-06-30-21-46-57-45_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/KanashiiDev/personal-stylesheets/assets/154865357/90cf7407-f3ee-4b02-a2c2-c93f0a5b6734)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser : KIWI (based on cromium)
 - Version : arm64-8822657649-github

**Smartphone (please complete the following information):**
- Android version: 14 (SDK 34; build OPD2203_14.0.0.610(EX01))
- Android build ID: OPD2203_14.0.0.610(EX01)
- Device brand: OnePlus
- Device manufacturer: OnePlus
- Device name: OP59BCL1 (OPD2203)
- Device model: OPD2203
- WebView: Android System WebView 126.0.6478.71

**Additional context**
Is there a way to make the redmarked ones like the green marked tags ? Or is it intended

**Comment by KanashiiDev** [comment] 2024-06-30 21:08
This bug was caused by [MAL-Clean-JS](https://github.com/KanashiiDev/MAL-Clean-JS/tree/main).  Fixed in version 1.27.8.

**Closed as completed** 2024-06-30 21:09 UTC

**Comment by p0bo** [comment] 2024-06-30 21:23
Thank you very much
